#!/bin/bash

export $(cat .env | xargs) &&
scp ~/prog/Internship-Autumn-ITTP/main.py $NAME@$IPAD:~/ &&
ssh $NAME@$IPAD "cd && python3 main.py>file.txt" &&
scp $NAME@$IPAD:~/file.txt ~/prog/Internship-Autumn-ITTP/ &&
cat file.txt
